### ISSUE TITLE
Give more information about tsk_system, user_code etc

### ISSUE THREAD

**Issue by DaniRusso13** [energicamotor/stm32-definitions#1]
"definition.h" is automatically added in the project when the folder is cloned, so if it's necessary this could be added in the code at least. In addition, I propose to add the common use of the tamplate just to have good overview. @Sykez42

**Comment by Sykez42** [comment]
@DaniRusso13 do you mind giving me a short description of the common use for the templates?

**Comment by DaniRusso13** [comment]
Could we add:
- tsk_system.c-> when the freeRTOS is defined, tsk_system is needed because it is the entry function of the OS (it's defined as weak);
- user_code.c/user_code.h ->inside of these are definide three functions (user_code_initialize, user_code_experiment_pre and user_code_experiment_post) which can be useful to use it instead of writing everything into the main.c. After the inclusion is done, these three functions needs to be added in entry main.
- ... others are specific when we need to add other task in the app code or base code
